# Generated by Django 4.2.6 on 2023-10-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iohunt', '0006_alter_puzzle_link_alter_puzzle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='link',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
