# Generated by Django 4.2.5 on 2023-10-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iganith', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='chance',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
