# Generated by Django 4.2.5 on 2023-10-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iganith', '0002_useranswer_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answered',
            field=models.ManyToManyField(null=True, to='iganith.question'),
        ),
    ]
