# Generated by Django 4.2.5 on 2023-10-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iganith', '0003_useranswer_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(default='', upload_to='iganithquestion'),
        ),
    ]
