# Generated by Django 4.2.5 on 2023-10-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iganith', '0004_remove_question_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
    ]
