# Generated by Django 4.2.5 on 2023-10-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iganith', '0007_alter_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(max_length=3000, unique=True),
        ),
    ]
