# Generated by Django 4.2.5 on 2023-10-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iganith', '0008_alter_question_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='just_answered',
            field=models.ManyToManyField(null=True, related_name='only_answered', to='iganith.question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answered',
            field=models.ManyToManyField(null=True, related_name='correctanswered', to='iganith.question'),
        ),
    ]
