# Generated by Django 4.2.5 on 2023-10-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iganith', '0011_alter_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='chance',
            field=models.IntegerField(default=4, null=True),
        ),
    ]
