# Generated by Django 4.2.5 on 2023-11-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iganith", "0012_alter_useranswer_chance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_image",
            field=models.ImageField(
                default="", upload_to="../ifest2023/static/images/iganithquestion"
            ),
        ),
    ]
