# Generated by Django 4.2.5 on 2023-11-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iganith", "0013_alter_question_question_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_image",
            field=models.ImageField(default="", upload_to="iganithquestion"),
        ),
    ]
